start /b AlarmCopyChamber_01.bat
start /b AlarmCopyChamber_02.bat
start /b AlarmCopyChamber_03.bat
start /b AlarmCopyChamber_04.bat
start /b AlarmCopyChamber_05.bat
start /b AlarmCopyChamber_06.bat
start /b AlarmCopyChamber_07.bat
start /b AlarmCopyChamber_08.bat
start /b AlarmCopyChamber_09.bat
start /b AlarmCopyChamber_10.bat
