start /b /d "C:\Users\chamber\Documents\Chamber data copy bat\" CopyChamber_01.bat
start /b /d "C:\Users\chamber\Documents\Chamber data copy bat\"  CopyChamber_02.bat
start /b /d "C:\Users\chamber\Documents\Chamber data copy bat\"  CopyChamber_03.bat
start /b /d "C:\Users\chamber\Documents\Chamber data copy bat\"  CopyChamber_04.bat
start /b /d "C:\Users\chamber\Documents\Chamber data copy bat\"  CopyChamber_05.bat
start /b /d "C:\Users\chamber\Documents\Chamber data copy bat\"  CopyChamber_06.bat
start /b /d "C:\Users\chamber\Documents\Chamber data copy bat\"  CopyChamber_07.bat
start /b /d "C:\Users\chamber\Documents\Chamber data copy bat\"  CopyChamber_08.bat
start /b /d "C:\Users\chamber\Documents\Chamber data copy bat\"  CopyChamber_09.bat
start /b /d "C:\Users\chamber\Documents\Chamber data copy bat\"  CopyChamber_10.bat 
